### ISSUE TITLE
Копирайт

### ISSUE THREAD

**Issue by DonDanon** [NeloExt3/neloext3.github.io#1]
Мне похер на твой копирайт
Я спизжу его и сделаю так чтобы вообще было не заметно что он спизжен!
И я скажу что я сделал сам как у кислого и ты доказать нечего не сможешь :>

**Comment by NeloExt3** [comment]
Я буду вынужден обратится в суд

**Comment by DonDanon** [comment]
Наркоман

**Comment by vladciphersky** [comment]
Ору
